### ISSUE TITLE
Code is built twice

### ISSUE THREAD

**Issue by abailly** [ndmitchell/bake#26]
With newer bake versions code is now built twice and I have two lines for each patch on the UI: 

![screen shot 2015-08-28 at 13 02 59](https://cloud.githubusercontent.com/assets/40221/9544939/26adf45a-4d85-11e5-854d-210de3bfcbfc.png)

One titled `patch` and one titled `state`. I am not sure I understand what's going on...

**Comment by ndmitchell** [comment]
That's deliberate. The idea is that I test a particular patch, and then apply it to produce a new state. At that point, if Bake has no other useful tasks it could do, it just tests the state it just produced. You expect that to succeed because the patch already succeeded, but if it doesn't, then you have a non-deterministic test. So it's just an extra check it does when it is otherwise idle. How come its failing for you? Is that a bug in your test?

**Comment by ndmitchell** [comment]
If it's harmful, I'd like to understand why, but I'm not averse to making it possible to turn off.

**Comment by abailly** [comment]
I understand the rationale, but then I would rather have a different set of "tests": what's the point of running the same tests against the same state? Sure, this can highlight flackiness of tests but this will show up under other circumstances. My main concern is waste : some of our "tests" push stuff to other servers and I don't want this action to be done twice. 

Our tests are far from being perfect but in this case, it failed because of download issue of a dependency, which is in itself a problem but unrelated to bake I think.

Would it be complicated to be able to define two set of tests: one for "patch" and one for "state"?

**Comment by ndmitchell** [comment]
The purpose of running the same tests against the same state is to catch flaky tests - at work we have 1000+ tests, and anything with QuickCheck can be flakey (only fails on certain seeds). Certainly if the tests running take up other server resources, they should be disabled. You don't want to run tests in the state which don't run in the patch, since if they fail, you can't reject anything (it just emails the admins to take appropriate action, assuming a flakey test). I see two options:

* Define an option to test the state or not - so you can just not test the state at all.
* Define an attribute to tests which makes them not run in the state - so the patch is always a superset.

Thoughts? If the state tests are of no use to you at all, the first is probably easier, but the second shouldn't be that hard anyway.

**Comment by abailly** [comment]
Flaky/intermittent tests are another problem that will always surface in
one way or another : on the dev env of developers, because of Chnages in
env... I do not think rerunning them twice is a good strategy against that
problem.

On the other hand I like the idea of having "tests" to run after merge, and
I put quotes because these aren't really tests : might be deployment stuff,
stats gathering, packaging, whatever... things that should not prevent a
patch to reach main branch because their failure does not mean there is a
problem in the codeine per se but rather come from the distributed nature
of the system : things will fail no matter what.

Thinking about it further, we might even think of having tests that would
reject the patch if bake would run against arbitrary code and not a commit
in a branch, thus enabling things like private CI builds or preflight
checks.

IMHO there are various phases in the integration process that each can have
their own set of states, so I would imagine that the function defining the
tests to run could take some context parameters to decide.0



Le vendredi 28 août 2015, Neil Mitchell <notifications@github.com> a écrit :

> The purpose of running the same tests against the same state is to catch
> flaky tests - at work we have 1000+ tests, and anything with QuickCheck can
> be flakey (only fails on certain seeds). Certainly if the tests running
> take up other server resources, they should be disabled. You don't want to
> run tests in the state which don't run in the patch, since if they fail,
> you can't reject anything (it just emails the admins to take appropriate
> action, assuming a flakey test). I see two options:
>
>    - Define an option to test the state or not - so you can just not test
>    the state at all.
>    - Define an attribute to tests which makes them not run in the state -
>    so the patch is always a superset.
>
> Thoughts? If the state tests are of no use to you at all, the first is
> probably easier, but the second shouldn't be that hard anyway.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ndmitchell/bake/issues/26#issuecomment-135887226>.
>


-- 
-- 
Arnaud Bailly

twitter: abailly
skype: arnaud-bailly
linkedin: http://fr.linkedin.com/in/arnaudbailly/

**Comment by ndmitchell** [comment]
Running the tests twice in our environment has been very valuable and already shown up quite a few issues. It only does so when there is nothing else to run, so in our setup they are basically "for free", and then even small benefits are worth it.

Note these State operations only run if there is nothing else pending, so as they stand, you couldn't use them for doing post-deployment things. If that was required, they'd have to become non-optional, in which case doing it in the merge operation itself might be more sense (if their failure is not harmful then using a `catch` could suppress those errors).

Having preflight checks etc only works if you don't do the preemptive combining of patches, so I think it is a useful feature, but I'm, not yet sure how it should fit into Bake.
