### ISSUE TITLE
Problems building on ghc-7.8.4

### ISSUE THREAD

**Issue by boothead** [ndmitchell/bake#37]
Hi,

I have problems building with ghc-7.8.4 on a couple of different environments. First I tried on an old RH box (you probably know the one). I then tried on my nixos box using stack. In both of these cases I get:

```
/home/ben/dev/haskell/bake/src/General/HTML.hs:76:15:
    No instance for (Eq
                       (WriterT Rope Data.Functor.Identity.Identity a))
      arising from the 'deriving' clause of a data type declaration
    Possible fix:
      use a standalone 'deriving instance' declaration,
        so you can specify the instance context yourself
    When deriving the instance for (Eq (HTML_ a))

/home/ben/dev/haskell/bake/src/General/HTML.hs:76:18:
    No instance for (Ord
                       (WriterT Rope Data.Functor.Identity.Identity a))
      arising from the 'deriving' clause of a data type declaration
    Possible fix:
      use a standalone 'deriving instance' declaration,
        so you can specify the instance context yourself
    When deriving the instance for (Ord (HTML_ a))

```

This seems to be needing base-4.9.0.0 to work as base-4.7.0.1 doens't have the Ord1 instance for Identity.

The ghc environment on this machine seem... quirky... though.

**Comment by boothead** [comment]
Actually base-4.8 and higher should be high enough.

**Comment by ndmitchell** [comment]
Are you using bake from HEAD or Hackage? I strongly recommend the HEAD version.

You can't mix and match GHC versions and base versions - there's no way to change the base version installed, so I don't see how your base/GHC can get out of alignment. I've just run the buildbot (https://travis-ci.org/ndmitchell/bake) and it successfully compiles on 7.6 to GHC Head (the errors are all due to insufficient doc comments), so I guess the question is what is different with your setup. Which version of transformers do you have? Any chance it is 0.3 or before? If you upgrade to a newer one that should probably work. If that works for you, I'll change the bounds. If not, I can write those instances by hand and we can avoid the transformers-0.4+ dependency.

**Comment by boothead** [comment]
I'll have a look later. BTW how did you get around compiling cryptonite on that special, old red hat box? I'm getting `cc1: error: unrecognized command line option "-maes"`, I assume due to an old gcc...

**Comment by ndmitchell** [comment]
Mostly by asking @vincenthz, I also wrote it down on the JIRA related to Hoogle. I think the magic was something like `-fold_toolchain_inliner` when configuring cryptonite.

**Comment by boothead** [comment]
I was on transformers-3. I've upgraded to 0.5.2.0 and everything is now working :-)

**Comment by ndmitchell** [comment]
Dependency added. Let me know if you have any other problems.
